"""Vendor framework logos from Simple Icons into the dashboard's static files.

The dashboard loads no external assets, so the icons are committed rather than
linked from a CDN: the page has to render identically offline, and a dev tool
should not phone out to a third party on every load.

Simple Icons rather than devicon because every icon there is a single path with
no hard-coded colour, so the logos inherit ``currentColor``. That lets them sit
directly on the dark surface -- tinted with the rest of the interface, and dimmed
along with a stopped route's card -- instead of needing a light tile behind each
one to stay legible.

Run it after adding a framework preset:

    uv run python scripts/vendor_icons.py

Simple Icons is CC0; the brand marks themselves remain their owners'. See
static/icons/LICENSE.
"""

from __future__ import annotations

import io
import json
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

REGISTRY = "https://registry.npmjs.org/simple-icons"
STATIC = Path(__file__).resolve().parent.parent / "src/vibe_caddy/dashboard/static"
ICONS = STATIC / "icons"

#: Framework preset name -> Simple Icons slug. Several presets share a mark:
#: there is no uvicorn logo, so it shows Python's.
MAPPING = {
    "angular": "angular",
    "astro": "astro",
    "django": "django",
    "express": "express",
    "fastapi": "fastapi",
    "flask": "flask",
    "go": "go",
    "gradio": "gradio",
    "hugo": "hugo",
    "jekyll": "jekyll",
    "next": "nextdotjs",
    "nuxt": "nuxt",
    "php": "php",
    "rails": "rubyonrails",
    "react-router": "reactrouter",
    "static": "html5",
    "streamlit": "streamlit",
    "sveltekit": "svelte",
    "uvicorn": "python",
    "vite": "vite",
}

#: An SVG is markup the browser parses in our own origin, so anything
#: scriptable is rejected rather than committed.
UNSAFE = re.compile(r"<script|\son\w+\s*=|javascript:|<foreignObject", re.IGNORECASE)


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=60) as response:  # noqa: S310 - fixed https host
        return response.read()


def main() -> int:
    meta = json.loads(fetch(REGISTRY))
    version = meta["dist-tags"]["latest"]
    print(f"simple-icons {version}")

    archive = tarfile.open(fileobj=io.BytesIO(fetch(meta["versions"][version]["dist"]["tarball"])))
    members = {Path(m.name).name: m for m in archive.getmembers() if m.name.endswith(".svg")}

    ICONS.mkdir(parents=True, exist_ok=True)
    for stale in ICONS.glob("*.svg"):
        stale.unlink()

    failures: list[str] = []
    written: list[str] = []

    for preset, slug in sorted(MAPPING.items()):
        member = members.get(f"{slug}.svg")
        if member is None:
            failures.append(f"{preset}: simple-icons has no icon {slug!r}")
            continue
        handle = archive.extractfile(member)
        if handle is None:
            failures.append(f"{preset}: could not read {slug}.svg")
            continue

        svg = handle.read()
        text = svg.decode("utf-8")
        if UNSAFE.search(text):
            failures.append(f"{preset}: {slug}.svg contains scriptable markup")
            continue
        # A hard-coded fill would defeat the point: these are tinted by CSS.
        if "fill=" in text or "#" in text:
            failures.append(f"{preset}: {slug}.svg is not monochrome")
            continue

        (ICONS / f"{preset}.svg").write_bytes(svg)
        written.append(preset)
        print(f"  {preset:14} <- {slug}.svg ({len(svg)} bytes)")

    # The logos are applied as CSS masks so they can take `currentColor`. The
    # rules are generated into a stylesheet rather than set as inline style
    # attributes, which the dashboard's Content-Security-Policy forbids.
    rules = "\n".join(
        f'.logo[data-framework="{name}"] {{ --logo: url("icons/{name}.svg"); }}' for name in written
    )
    (STATIC / "icons.css").write_text(
        "/* Generated by scripts/vendor_icons.py. Do not edit.\n"
        "   One mask source per framework; see .logo in app.css. */\n" + rules + "\n"
    )

    (ICONS / "LICENSE").write_text(
        f"The .svg files in this directory are from Simple Icons {version}\n"
        "(https://simpleicons.org), released under CC0 1.0 Universal.\n\n"
        "The brand marks they depict remain the property of their respective\n"
        "owners; CC0 covers the icon files, not the trademarks.\n\n"
        "Regenerate with: uv run python scripts/vendor_icons.py\n"
    )

    for failure in failures:
        print(f"FAILED {failure}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
